// Code generated by protoc-gen-go. DO NOT EDIT.
// source: employee/employee.proto

package employeepb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Employee struct {
	Id                   int32      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address              []*Address `protobuf:"bytes,3,rep,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Employee) Reset()         { *m = Employee{} }
func (m *Employee) String() string { return proto.CompactTextString(m) }
func (*Employee) ProtoMessage()    {}
func (*Employee) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5faaaf42a8ac842, []int{0}
}

func (m *Employee) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Employee.Unmarshal(m, b)
}
func (m *Employee) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Employee.Marshal(b, m, deterministic)
}
func (m *Employee) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Employee.Merge(m, src)
}
func (m *Employee) XXX_Size() int {
	return xxx_messageInfo_Employee.Size(m)
}
func (m *Employee) XXX_DiscardUnknown() {
	xxx_messageInfo_Employee.DiscardUnknown(m)
}

var xxx_messageInfo_Employee proto.InternalMessageInfo

func (m *Employee) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Employee) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Employee) GetAddress() []*Address {
	if m != nil {
		return m.Address
	}
	return nil
}

type Address struct {
	AddressLane1         string   `protobuf:"bytes,1,opt,name=address_lane1,json=addressLane1,proto3" json:"address_lane1,omitempty"`
	AddressLane2         string   `protobuf:"bytes,2,opt,name=address_lane2,json=addressLane2,proto3" json:"address_lane2,omitempty"`
	City                 string   `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	State                string   `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	Country              string   `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"`
	Zipcode              string   `protobuf:"bytes,6,opt,name=zipcode,proto3" json:"zipcode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Address) Reset()         { *m = Address{} }
func (m *Address) String() string { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()    {}
func (*Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5faaaf42a8ac842, []int{1}
}

func (m *Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Address.Unmarshal(m, b)
}
func (m *Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Address.Marshal(b, m, deterministic)
}
func (m *Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Address.Merge(m, src)
}
func (m *Address) XXX_Size() int {
	return xxx_messageInfo_Address.Size(m)
}
func (m *Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Address proto.InternalMessageInfo

func (m *Address) GetAddressLane1() string {
	if m != nil {
		return m.AddressLane1
	}
	return ""
}

func (m *Address) GetAddressLane2() string {
	if m != nil {
		return m.AddressLane2
	}
	return ""
}

func (m *Address) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Address) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Address) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Address) GetZipcode() string {
	if m != nil {
		return m.Zipcode
	}
	return ""
}

type EmployeeRequest struct {
	Employee             *Employee `protobuf:"bytes,1,opt,name=employee,proto3" json:"employee,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *EmployeeRequest) Reset()         { *m = EmployeeRequest{} }
func (m *EmployeeRequest) String() string { return proto.CompactTextString(m) }
func (*EmployeeRequest) ProtoMessage()    {}
func (*EmployeeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5faaaf42a8ac842, []int{2}
}

func (m *EmployeeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmployeeRequest.Unmarshal(m, b)
}
func (m *EmployeeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmployeeRequest.Marshal(b, m, deterministic)
}
func (m *EmployeeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmployeeRequest.Merge(m, src)
}
func (m *EmployeeRequest) XXX_Size() int {
	return xxx_messageInfo_EmployeeRequest.Size(m)
}
func (m *EmployeeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmployeeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmployeeRequest proto.InternalMessageInfo

func (m *EmployeeRequest) GetEmployee() *Employee {
	if m != nil {
		return m.Employee
	}
	return nil
}

type EmployeeResponse struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmployeeResponse) Reset()         { *m = EmployeeResponse{} }
func (m *EmployeeResponse) String() string { return proto.CompactTextString(m) }
func (*EmployeeResponse) ProtoMessage()    {}
func (*EmployeeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5faaaf42a8ac842, []int{3}
}

func (m *EmployeeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmployeeResponse.Unmarshal(m, b)
}
func (m *EmployeeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmployeeResponse.Marshal(b, m, deterministic)
}
func (m *EmployeeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmployeeResponse.Merge(m, src)
}
func (m *EmployeeResponse) XXX_Size() int {
	return xxx_messageInfo_EmployeeResponse.Size(m)
}
func (m *EmployeeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EmployeeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EmployeeResponse proto.InternalMessageInfo

func (m *EmployeeResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*Employee)(nil), "employee.Employee")
	proto.RegisterType((*Address)(nil), "employee.Address")
	proto.RegisterType((*EmployeeRequest)(nil), "employee.EmployeeRequest")
	proto.RegisterType((*EmployeeResponse)(nil), "employee.EmployeeResponse")
}

func init() { proto.RegisterFile("employee/employee.proto", fileDescriptor_d5faaaf42a8ac842) }

var fileDescriptor_d5faaaf42a8ac842 = []byte{
	// 293 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x51, 0x4d, 0x4b, 0xc3, 0x40,
	0x14, 0x34, 0x4d, 0xd3, 0xb4, 0xaf, 0xf5, 0x6b, 0x11, 0x5c, 0x7b, 0x0a, 0x11, 0x24, 0x20, 0x44,
	0x8c, 0xbf, 0xa0, 0x8a, 0x37, 0x4f, 0x11, 0x3c, 0xe8, 0x41, 0xb6, 0xd9, 0x77, 0x08, 0xb4, 0xd9,
	0x98, 0xdd, 0x0a, 0xf1, 0x5f, 0xf9, 0x0f, 0x25, 0xfb, 0x91, 0x14, 0xe9, 0x6d, 0xde, 0xcc, 0xb0,
	0x33, 0xfb, 0x1e, 0x5c, 0xe2, 0xb6, 0xde, 0x88, 0x16, 0xf1, 0xce, 0x81, 0xb4, 0x6e, 0x84, 0x12,
	0x64, 0xea, 0xe6, 0xf8, 0x03, 0xa6, 0xcf, 0x16, 0x93, 0x13, 0x18, 0x95, 0x9c, 0x7a, 0x91, 0x97,
	0x04, 0xf9, 0xa8, 0xe4, 0x84, 0xc0, 0xb8, 0x62, 0x5b, 0xa4, 0xa3, 0xc8, 0x4b, 0x66, 0xb9, 0xc6,
	0xe4, 0x16, 0x42, 0xc6, 0x79, 0x83, 0x52, 0x52, 0x3f, 0xf2, 0x93, 0x79, 0x76, 0x9e, 0xf6, 0x6f,
	0xaf, 0x8c, 0x90, 0x3b, 0x47, 0xfc, 0xeb, 0x41, 0x68, 0x49, 0x72, 0x0d, 0xc7, 0x96, 0xfe, 0xdc,
	0xb0, 0x0a, 0xef, 0x75, 0xce, 0x2c, 0x5f, 0x58, 0xf2, 0xa5, 0xe3, 0xfe, 0x9b, 0x32, 0x1b, 0xbd,
	0x6f, 0xca, 0xba, 0x5a, 0x45, 0xa9, 0x5a, 0xea, 0x9b, 0x5a, 0x1d, 0x26, 0x17, 0x10, 0x48, 0xc5,
	0x14, 0xd2, 0xb1, 0x26, 0xcd, 0x40, 0x28, 0x84, 0x85, 0xd8, 0x55, 0xaa, 0x69, 0x69, 0xa0, 0x79,
	0x37, 0x76, 0xca, 0x4f, 0x59, 0x17, 0x82, 0x23, 0x9d, 0x18, 0xc5, 0x8e, 0xf1, 0x0a, 0x4e, 0xdd,
	0x42, 0x72, 0xfc, 0xda, 0xa1, 0x54, 0x24, 0x85, 0x7e, 0x5f, 0xba, 0xf5, 0x3c, 0x23, 0xc3, 0xa7,
	0x7b, 0xf3, 0xb0, 0xd3, 0x1b, 0x38, 0x1b, 0x9e, 0x90, 0xb5, 0xa8, 0x24, 0x76, 0xa5, 0x39, 0x53,
	0xcc, 0xfe, 0x5a, 0xe3, 0xec, 0x6d, 0x88, 0x7a, 0xc5, 0xe6, 0xbb, 0x2c, 0x90, 0x3c, 0xed, 0x9d,
	0xe3, 0xea, 0x40, 0x88, 0x69, 0xb4, 0x5c, 0x1e, 0x92, 0x4c, 0x52, 0x7c, 0xf4, 0xb8, 0x78, 0x07,
	0x27, 0xd7, 0xeb, 0xf5, 0x44, 0x9f, 0xfc, 0xe1, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xe3, 0x16, 0x7b,
	0x5c, 0x0d, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EmployeeServiceClient is the client API for EmployeeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EmployeeServiceClient interface {
	Employee(ctx context.Context, in *EmployeeRequest, opts ...grpc.CallOption) (*EmployeeResponse, error)
}

type employeeServiceClient struct {
	cc *grpc.ClientConn
}

func NewEmployeeServiceClient(cc *grpc.ClientConn) EmployeeServiceClient {
	return &employeeServiceClient{cc}
}

func (c *employeeServiceClient) Employee(ctx context.Context, in *EmployeeRequest, opts ...grpc.CallOption) (*EmployeeResponse, error) {
	out := new(EmployeeResponse)
	err := c.cc.Invoke(ctx, "/employee.EmployeeService/Employee", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmployeeServiceServer is the server API for EmployeeService service.
type EmployeeServiceServer interface {
	Employee(context.Context, *EmployeeRequest) (*EmployeeResponse, error)
}

// UnimplementedEmployeeServiceServer can be embedded to have forward compatible implementations.
type UnimplementedEmployeeServiceServer struct {
}

func (*UnimplementedEmployeeServiceServer) Employee(ctx context.Context, req *EmployeeRequest) (*EmployeeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Employee not implemented")
}

func RegisterEmployeeServiceServer(s *grpc.Server, srv EmployeeServiceServer) {
	s.RegisterService(&_EmployeeService_serviceDesc, srv)
}

func _EmployeeService_Employee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmployeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeServiceServer).Employee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/employee.EmployeeService/Employee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeServiceServer).Employee(ctx, req.(*EmployeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _EmployeeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "employee.EmployeeService",
	HandlerType: (*EmployeeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Employee",
			Handler:    _EmployeeService_Employee_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "employee/employee.proto",
}
