// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user/userpb/user.proto

package userpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	FirstName            string     `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string     `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email                string     `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Username             string     `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Password             string     `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	Address              []*Address `protobuf:"bytes,6,rep,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c4d46a2d91a774f, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetAddress() []*Address {
	if m != nil {
		return m.Address
	}
	return nil
}

type Address struct {
	AddressLane1         string   `protobuf:"bytes,1,opt,name=address_lane1,json=addressLane1,proto3" json:"address_lane1,omitempty"`
	AddressLane2         string   `protobuf:"bytes,2,opt,name=address_lane2,json=addressLane2,proto3" json:"address_lane2,omitempty"`
	City                 string   `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	State                string   `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	Country              string   `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"`
	Zipcode              string   `protobuf:"bytes,6,opt,name=zipcode,proto3" json:"zipcode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Address) Reset()         { *m = Address{} }
func (m *Address) String() string { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()    {}
func (*Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c4d46a2d91a774f, []int{1}
}

func (m *Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Address.Unmarshal(m, b)
}
func (m *Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Address.Marshal(b, m, deterministic)
}
func (m *Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Address.Merge(m, src)
}
func (m *Address) XXX_Size() int {
	return xxx_messageInfo_Address.Size(m)
}
func (m *Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Address proto.InternalMessageInfo

func (m *Address) GetAddressLane1() string {
	if m != nil {
		return m.AddressLane1
	}
	return ""
}

func (m *Address) GetAddressLane2() string {
	if m != nil {
		return m.AddressLane2
	}
	return ""
}

func (m *Address) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Address) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Address) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Address) GetZipcode() string {
	if m != nil {
		return m.Zipcode
	}
	return ""
}

type UserRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRequest) Reset()         { *m = UserRequest{} }
func (m *UserRequest) String() string { return proto.CompactTextString(m) }
func (*UserRequest) ProtoMessage()    {}
func (*UserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c4d46a2d91a774f, []int{2}
}

func (m *UserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRequest.Unmarshal(m, b)
}
func (m *UserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRequest.Marshal(b, m, deterministic)
}
func (m *UserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRequest.Merge(m, src)
}
func (m *UserRequest) XXX_Size() int {
	return xxx_messageInfo_UserRequest.Size(m)
}
func (m *UserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserRequest proto.InternalMessageInfo

func (m *UserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UserResponse struct {
	UserResponse         string   `protobuf:"bytes,1,opt,name=user_response,json=userResponse,proto3" json:"user_response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c4d46a2d91a774f, []int{3}
}

func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (m *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(m, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetUserResponse() string {
	if m != nil {
		return m.UserResponse
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "user.User")
	proto.RegisterType((*Address)(nil), "user.Address")
	proto.RegisterType((*UserRequest)(nil), "user.UserRequest")
	proto.RegisterType((*UserResponse)(nil), "user.UserResponse")
}

func init() { proto.RegisterFile("user/userpb/user.proto", fileDescriptor_9c4d46a2d91a774f) }

var fileDescriptor_9c4d46a2d91a774f = []byte{
	// 331 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x92, 0x31, 0x4f, 0xfb, 0x30,
	0x10, 0xc5, 0xff, 0xf9, 0x37, 0x4d, 0xdb, 0x6b, 0x3b, 0x60, 0x21, 0x14, 0x15, 0x81, 0xaa, 0x30,
	0xd0, 0x85, 0x56, 0xa4, 0x3b, 0x12, 0xcc, 0x88, 0xa1, 0x88, 0x85, 0xa5, 0x72, 0x93, 0x43, 0x8a,
	0xd4, 0xc6, 0xc1, 0x76, 0x40, 0xe5, 0x5b, 0x31, 0xf2, 0xed, 0x90, 0xef, 0x6c, 0x29, 0x62, 0x49,
	0xfc, 0x7e, 0xef, 0x9c, 0xf3, 0xcb, 0x19, 0xce, 0x5a, 0x83, 0x7a, 0xe5, 0x1e, 0xcd, 0x8e, 0x5e,
	0xcb, 0x46, 0x2b, 0xab, 0x44, 0xec, 0xd6, 0xd9, 0x4f, 0x04, 0xf1, 0x8b, 0x41, 0x2d, 0x2e, 0x00,
	0xde, 0x2a, 0x6d, 0xec, 0xb6, 0x96, 0x07, 0x4c, 0xa3, 0x79, 0xb4, 0x18, 0x6d, 0x46, 0x44, 0x9e,
	0xe4, 0x01, 0xc5, 0x39, 0x8c, 0xf6, 0x32, 0xb8, 0xff, 0xc9, 0x1d, 0x3a, 0x40, 0xe6, 0x29, 0xf4,
	0xf1, 0x20, 0xab, 0x7d, 0xda, 0x23, 0x83, 0x85, 0x98, 0xc1, 0xd0, 0xb5, 0xa0, 0x1d, 0x31, 0xef,
	0x08, 0xda, 0x79, 0x8d, 0x34, 0xe6, 0x53, 0xe9, 0x32, 0xed, 0xb3, 0x17, 0xb4, 0xb8, 0x86, 0x81,
	0x2c, 0x4b, 0x8d, 0xc6, 0xa4, 0xc9, 0xbc, 0xb7, 0x18, 0xe7, 0xd3, 0x25, 0x1d, 0xfb, 0x9e, 0xe1,
	0x26, 0xb8, 0xd9, 0x77, 0x04, 0x03, 0x0f, 0xc5, 0x15, 0x4c, 0x3d, 0xde, 0xee, 0x65, 0x8d, 0xb7,
	0x3e, 0xc1, 0xc4, 0xc3, 0x47, 0xc7, 0xfe, 0x16, 0xe5, 0x3e, 0x48, 0xb7, 0x28, 0x17, 0x02, 0xe2,
	0xa2, 0xb2, 0x47, 0x9f, 0x85, 0xd6, 0x2e, 0xa0, 0xb1, 0xd2, 0x86, 0x1c, 0x2c, 0x44, 0x0a, 0x83,
	0x42, 0xb5, 0xb5, 0xd5, 0x47, 0x9f, 0x21, 0x48, 0xe7, 0x7c, 0x55, 0x4d, 0xa1, 0x4a, 0x4c, 0x13,
	0x76, 0xbc, 0xcc, 0x6e, 0x60, 0xec, 0x7e, 0xf7, 0x06, 0xdf, 0x5b, 0x34, 0x56, 0x5c, 0x02, 0x8d,
	0x81, 0x4e, 0x3b, 0xce, 0x81, 0x83, 0x52, 0x01, 0x8f, 0x67, 0x0d, 0x13, 0x2e, 0x37, 0x8d, 0xaa,
	0x0d, 0xba, 0x04, 0x8e, 0x6f, 0xb5, 0x07, 0x21, 0x66, 0xdb, 0x29, 0xca, 0xef, 0xb8, 0xc7, 0x33,
	0xea, 0x8f, 0xaa, 0x40, 0xb1, 0xf2, 0x13, 0x3e, 0xe9, 0x7c, 0x9d, 0xdb, 0xcf, 0x44, 0x17, 0xf1,
	0xee, 0xec, 0xdf, 0xc3, 0xf0, 0x35, 0xe1, 0xeb, 0xb2, 0x4b, 0xe8, 0xaa, 0xac, 0x7f, 0x03, 0x00,
	0x00, 0xff, 0xff, 0x66, 0x48, 0xf4, 0xf9, 0x44, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	User(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) User(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/User", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	User(context.Context, *UserRequest) (*UserResponse, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) User(ctx context.Context, req *UserRequest) (*UserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method User not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_User_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).User(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/User",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).User(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "User",
			Handler:    _UserService_User_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user/userpb/user.proto",
}
